# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3caacac4ea2c2ccc97bea9d7a1b78d50b7520f8328d71d3642cc51398744598ecc471b1197d311ff4f4f840d956cef30a0c080963f3f100791edc0d764981a72

test:
  secret_key_base: bf5ffa5089f3a6304109810a5a41cce2b23f2fe7f549c3a16e7f4e329d421a586c33c7bb12a0382dfe8fe7df37f8ab65207e5ab6ffcc34cc6d36afbb63e23400

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
